spring.application.name=blelocation-api
spring.datasource.url=jdbc:postgresql://localhost:5432/blelocation_db
spring.datasource.username=toge
spring.datasource.password=togepass
# ↓createは起動するたびに作り直す。本番ではupdateにするべき
spring.jpa.hibernate.ddl-auto=create

# 裏で流れるSQL文が見れる（任意）
spring.jpa.show-sql=true	
# 整形されて表示される（任意）
spring.jpa.properties.hibernate.format_sql=true